DELETE http://localhost:3003/api/blogs/68a8357af03a323e3874e0d5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY4NWZkYTIwN2Y3MTc5ZjU2OTY3YzVjNiIsImlhdCI6MTc1NTg1NDEzMn0.G7C2tHWbOiKOVQ0KZqyVP4xG3Mxl6QZV1Vbx1VMPXxw