POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvbWVndXkxIiwiaWQiOiI2ODVlNzE2NThlYTY5NjkyY2YzNDYxZGEiLCJpYXQiOjE3NTExMDI0NTV9.NdJnHZIrXpnGzehrSHndwsXiK_kUxD7OP8nC3Md4OYw

{
    "title": "Testi",
    "author": "Kirjoittaja",
    "url": "http://esim.fi",
    "likes": 3
}